CommentBundle\Entity\Comment:
  type: entity
  repositoryClass: CommentBundle\Repository\CommentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    postId:
      type: integer
      column: post_id
      nullable: false
    parentId:
      column: parent_id
      type: integer
      nullable: true
    votesRating:
      type: integer
      nullable: false
    votesPositive:
      type: integer
      nullable: false
    votesNegative:
      type: integer
      nullable: false
  manyToOne:
    profile:
      targetEntity: ProfileBundle\Entity\Profile
  manyToMany:
    attachments:
      targetEntity: AttachmentBundle\Entity\Attachment