feed:
  path: '/limit/{limit}/offset/{offset}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feed }
  requirements:
    limit: \d+
    offset: \d+

feed_total:
  path: '/total'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feedTotal }

profile_feed:
  path: '/profile/{id}/limit/{limit}/offset/{offset}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:ProfileFeed:feed }
  requirements:
    id: \d+
    limit: \d+
    offset: \d+

profile_feed_total:
  path: '/profile/{id}/total'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:ProfileFeed:feedTotal }
  requirements:
    id: \d+