feed:
  path: '/limit/{limit}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feed }
  requirements:
    limit: \d+
    cursor: \d+
    dateFrom: "*"
    dateTo: "*"
    profile: \d+
    order: "id|rating"
    direction: ASC|DESC

profile_feed:
  path: '/profile/{profileId}/limit/{limit}/offset/{offset}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:ProfileFeed:feed }
  requirements:
    profileId: \d+
    limit: \d+
    offset: \d+
