feed:
  path: '/limit/{limit}/cursor/{cursor}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feed }
  requirements:
    limit: \d+
    cursor: \d+
#    dateFrom: \d+
#    dateNow: \d+
#    profile: \d+
    order: "[a-z_]+"
    direction: ASC|DESC

feed_total:
  path: '/total'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feedTotal }

profile_feed:
  path: '/profile/{profileId}/limit/{limit}/offset/{offset}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:ProfileFeed:feed }
  requirements:
    profileId: \d+
    limit: \d+
    offset: \d+

profile_feed_total:
  path: '/profile/{id}/total'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:ProfileFeed:feedTotal }
  requirements:
    id: \d+