feed:
  path: '/limit/{limit}'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:feed }
  requirements:
    limit: \d+
    cursor: \d+
    dateFrom: "*"
    dateTo: "*"
    profile: \d+
    sort: "id|rating"
    direction: ASC|DESC

feed_hot:
  path: '/hot'
  methods: [ GET ]
  defaults: { _controller: FeedBundle:Feed:hotFeed }
