version: '2.1'
services:
  mysql:
    build: ./docker/mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_TEST_DATABASE: ${DB_TEST_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  nginx:
    build: ./docker/nginx
    ports: ["80:8080"]
    volumes:
      - ./src:/opt/jet
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on: [php]

  php:
    build: ./docker/php
    stdin_open: true
    volumes: 
      - ./src:/opt/jet
    depends_on: [mysql]