services:
    oauth.security.success_handler:
        class:  OAuthBundle\Handler\OAuthSuccessHandler
        arguments:
          - '@lexik_jwt_authentication.jwt_manager'
          - '@event_dispatcher'
          - '@router'    
    oauth.security.account_provider:
        class: OAuthBundle\Security\Core\Account\OAuthAccountProvider
        arguments:
            - '@fos_user.user_manager'
            - { vk: vkId, facebook: facebookId }        