imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: false
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

fos_user:
    db_driver: orm
    firewall_name: protected_api
    user_class: AccountBundle\Entity\Account
    from_email:
        address: "noreply@yourcompany.com"
        sender_name: "No Reply"
    registration:
        confirmation:
            enabled: true

nelmio_api_doc:
    name: JET-API
    sandbox:
        authentication:
            delivery: header
            name:     Authorization
        body_format:
            formats:
                - json
                - form
            default_format: "json"
        request_format:
            method: accept_header

hwi_oauth:
    firewall_names: [login_protected_api]
    resource_owners:
        vk:
            type:                vkontakte
            client_id:           '%hwi_oauth_vk_id%'
            client_secret:       '%hwi_oauth_vk_secret%'
            authorization_url:   "https://oauth.vk.com/authorize?display=mobile"
        facebook:
            type:                facebook
            client_id:           '%hwi_oauth_facebook_id%'
            client_secret:       '%hwi_oauth_facebook_secret%'
            scope:               "email,public_profile,user_birthday"
            authorization_url:   "https://www.facebook.com/v2.7/dialog/oauth?display=popup"
            
gesdinet_jwt_refresh_token:
    ttl: 2592000           
    user_provider: fos_user.user_provider.username_email

profile:
    limit: 1
    min_age: 13
    max_age: 150
    avatar:
      absolute_path: '%kernel.root_dir%/../../web/uploads/avatar'
      web_path: 'uploads/avatar'
      min_width: 200
      min_height: 200
      max_width: 7000
      max_height: 7000
      min_ratio: 0.25
      max_ratio: 3
    backdrop:
      absolute_path: '%kernel.root_dir%/../../web/uploads/backdrop'
      web_path: 'uploads/backdrop'
      min_width: 1500
      min_height: 300
      max_width: 7000
      max_height: 7000
      min_ratio: 3
      max_ratio: 3
      presets:
        1:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/1.jpg'
          web_path: 'bundles/profile/backdrop/presets/1.jpg'
        2:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/2.jpg'
          web_path: 'bundles/profile/backdrop/presets/2.jpg'
        3:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/3.jpg'
          web_path: 'bundles/profile/backdrop/presets/3.jpg'
        4:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/4.jpg'
          web_path: 'bundles/profile/backdrop/presets/4.jpg'
        5:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/5.jpg'
          web_path: 'bundles/profile/backdrop/presets/5.jpg'
        6:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/6.jpg'
          web_path: 'bundles/profile/backdrop/presets/6.jpg'
        7:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/7.jpg'
          web_path: 'bundles/profile/backdrop/presets/7.jpg'
        8:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/8.jpg'
          web_path: 'bundles/profile/backdrop/presets/8.jpg'
        9:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/9.jpg'
          web_path: 'bundles/profile/backdrop/presets/9.jpg'
        10:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/10.jpg'
          web_path: 'bundles/profile/backdrop/presets/10.jpg'
        11:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/11.jpg'
          web_path: 'bundles/profile/backdrop/presets/11.jpg'
        12:
          absolute_path: '%kernel.root_dir%/../../web/bundles/profile/backdrop/presets/12.jpg'
          web_path: 'bundles/profile/backdrop/presets/12.jpg'