NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc
  
auth:
  resource: '@AuthBundle/Resources/config/routing.yml'
  prefix:   /auth

oAuth:
  resource: '@OAuthBundle/Resources/config/routing.yml'
  prefix:   /oAuth