doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

auth:
  resource: '@AuthBundle/Resources/config/routing.yml'
  prefix:   /auth

oAuth:
  resource: '@OAuthBundle/Resources/config/routing.yml'
  prefix:   /oAuth

profile:
  resource: '@ProfileBundle/Resources/config/routing.yml'
  prefix: /profile

protected_profile:
  resource: '@ProfileBundle/Resources/config/routing_protected.yml'
  prefix: /protected/profile

  