doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

auth:
  resource: '@AuthBundle/Resources/config/routing.yml'
  prefix:   /auth

protected_auth:
  resource: '@AuthBundle/Resources/config/protected_routing.yml'
  prefix: /protected/auth

oAuth:
  resource: '@OAuthBundle/Resources/config/routing.yml'
  prefix:   /oAuth

profile:
  resource: '@ProfileBundle/Resources/config/routing.yml'
  prefix: /profile

protected_profile:
  resource: '@ProfileBundle/Resources/config/routing_protected.yml'
  prefix: /protected/profile

attachment:
  resource: '@AttachmentBundle/Resources/config/routing.yml'
  prefix: /attachment

protected_attachment:
  resource: '@AttachmentBundle/Resources/config/routing_protected.yml'
  prefix: /protected/attachment

post:
  resource: '@PostBundle/Resources/config/routing.yml'
  prefix: '/post'

protected_post:
  resource: '@PostBundle/Resources/config/routing_protected.yml'
  prefix: '/protected/post'

tag:
  resource: '@TagBundle/Resources/config/routing.yml'
  prefix: '/tag'

protected_tag:
  resource: '@TagBundle/Resources/config/routing_protected.yml'
  prefix: '/protected/tag'

feed:
  resource: '@FeedBundle/Resources/config/routing.yml'
  prefix: '/feed'

protected_feed:
  resource: '@FeedBundle/Resources/config/routing_protected.yml'
  prefix: '/protected/feed'

vote:
  resource: '@VoteBundle/Resources/config/routing.yml'
  prefix: '/vote'

protected_vote:
  resource: '@VoteBundle/Resources/config/routing_protected.yml'
  prefix: '/protected/vote'

comment:
  resource: '@CommentBundle/Resources/config/routing.yml'
  prefix: '/comment'

protected_comment:
  resource: '@CommentBundle/Resources/config/routing_protected.yml'
  prefix: '/protected/comment'

search:
  resource: '@SearchBundle/Resources/config/routing.yml'
  prefix: '/search'