# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_CREATED: ROLE_USER
        ROLE_REGISTERED: ROLE_CREATED
        ROLE_PHONE_VERIFED: ROLE_CREATED
        ROLE_EMAIL_VERIFED: ROLE_CREATED
        ROLE_VERIFED: ROLE_CREATED

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_protected_api:
            pattern: ^/(oA|a)uth
            anonymous: ~
            stateless: true
            jet_form_login:
                check_path:               /auth/sign-in
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
            oauth:
                login_path:   /oAuth
                check_path:   /oAuth
                oauth_user_provider:
                    service: security.oauth.account_provider.service
                resource_owners:
                    vk:       /oAuth/vk
                    facebook: /oAuth/facebook
                success_handler: security.oauth.success_handler

        protected_api:
            pattern: ^/protected
            anonymous: false
            stateless: true
            lexik_jwt: 
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                throw_exceptions:        false
                create_entry_point:      true