PostBundle\Entity\Post:
  type: entity
  repositoryClass: PostBundle\Repository\PostRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    title:
      type: string
      nullable: false
  manyToMany:
    tags:
      targetEntity: TagBundle\Entity\Tag
    attachments:
      targetEntity: AttachmentBundle\Entity\Attachment