PostBundle\Entity\Post:
  type: entity
  repositoryClass: PostBundle\Repository\PostRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    title:
      type: string
      nullable: false
    attachments:
      type: json_array
      nullable: true
  manyToMany:
    tags:
      targetEntity: TagBundle\Entity\Tag
      joinTable:
        name: post_tags
        joinColumns:
          post_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
