post_get_by_id:
  path: '{id}/get-by-id'
  methods: [ GET ]
  defaults: { _controller: PostBundle:Post:getById }

post_info_posts:
  path: 'info/type/{type}'
  methods: [ GET ]
  defaults: { _controller: PostBundle:InfoPosts:get }
