services:
  post.repository:
    class: PostBundle\Repository\PostRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - PostBundle\Entity\Post

  post.service:
    class: PostBundle\Service\PostService
    arguments:
      - '@post.repository'
      - '%post.max_tags_limit%'
      - '%post.max_attachments_limit%'

