AttachmentBundle\Entity\Attachment:
  type: entity
  repositoryClass: AttachmentBundle\Repository\AttachmentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    type:
      type: string
      nullable: false
    content:
      type: json_array
      nullable: true
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false