profile_get_by_id:
  path: '{id}/get-by-id'
  defaults: { _controller: ProfileBundle:Read:getById }
  requirements:
    id: '\d+'
  methods: [ GET ]

profile_get_by_alias:
  path: '{alias}/get-by-alias'
  defaults: { _controller: ProfileBundle:Read:getByAlias }
  requirements:
    alias: '\w+'
  methods: [ GET ]

