services:
  profile.repository:
    class: ProfileBundle\Repository\ProfileRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - ProfileBundle\Entity\Profile

  profile.service:
    class: ProfileBundle\Service\ProfileService
    arguments: 
      - '@profile.repository'
      - '@event_dispatcher'
      - '%profile.limit%'
      - '%profile.min_age%'
      - '%profile.max_age%'

  profile.event_listener.add_account_role_registered_listener:
    class: ProfileBundle\EventListener\AddAccountRoleRegisteredListener
    arguments: ['@auth.account.repository']
    tags:
      - { name: kernel.event_subscriber }