services:
  profile.repository:
    class: ProfileBundle\Repository\ProfileRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - ProfileBundle\Entity\Profile

  profile.service:
    class: ProfileBundle\Service\ProfileService
    calls:
      - [ setContainer, ['@service_container'] ]
    arguments: 
      - '@profile.repository'
      - '@auth.service'
      - '@event_dispatcher'
      - '%profile.limit%'
      
  profile.form.type:
    class: ProfileBundle\Form\ProfileType
    arguments:
      - '%profile.min_age%'
      - '%profile.max_age%'
    tags: [{name: form.type}]