services:
  profile.repository:
    class: ProfileBundle\Repository\ProfileRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - ProfileBundle\Entity\Profile

  profile.service:
    class: ProfileBundle\Service\ProfileService
    arguments: 
      - '@profile.repository'
      - '@auth.service'
      - '@event_dispatcher'
      - '%profile.limit%'
      
  profile.form.type:
    class: ProfileBundle\Form\AbsctractProfileType
    abstract: true
    arguments:
      - '%profile.min_age%'
      - '%profile.max_age%'

  profile.create.form.type:
    class: ProfileBundle\Form\ProfileCreateType
    parent: profile.form.type 
    tags: [{name: form.type}]

  profile.update.form.type:
    class: ProfileBundle\Form\ProfileUpdateType
    parent: profile.form.type 
    tags: [{name: form.type}]