services:
  profile.repository:
    class: ProfileBundle\Repository\ProfileRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - ProfileBundle\Entity\Profile

  profile.service:
    class: ProfileBundle\Service\ProfileService
    calls:
      - [ setContainer, ['@service_container'] ]
    arguments: 
      - '@profile.repository'
      - '@auth.service'
      - '@event_dispatcher'
      - '%profile.limit%'
      
  profile.form.type:
    class: ProfileBundle\Form\ProfileType
    arguments:
      - '%profile.min_age%'
      - '%profile.max_age%'
    tags: [{name: form.type}]

  profile.form.backdrop_upload_type:
    class: ProfileBundle\Form\BackdropUploadType
    arguments:
      - '%profile.backdrop.min_width%'
      - '%profile.backdrop.max_width%'
      - '%profile.backdrop.min_height%'
      - '%profile.backdrop.max_height%'
      - '%profile.backdrop.min_ratio%'
      - '%profile.backdrop.max_ratio%'
    tags: [{name: form.type}]

  profile.form.avatar_upload_type:
    class: ProfileBundle\Form\AvatarUploadType
    arguments:
      - '%profile.avatar.min_width%'
      - '%profile.avatar.max_width%'
      - '%profile.avatar.min_height%'
      - '%profile.avatar.max_height%'
      - '%profile.avatar.min_ratio%'
      - '%profile.avatar.max_ratio%'
    tags: [{name: form.type}]

