vote_post_positive:
  methods: [ POST ]
  path: /post/{postId}/positive
  defaults: { _controller: VoteBundle:PostVote:votePositive }
  requirements:
    postId: \d+

vote_post_negative:
  methods: [ POST ]
  path: /post/{postId}/negative
  defaults: { _controller: VoteBundle:PostVote:voteNegative }
  requirements:
    postId: \d+

vote_post_delete:
  methods: [ DELETE ]
  path: /post/{postId}/delete
  defaults: { _controller: VoteBundle:PostVote:voteRemove }
  requirements:
    postId: \d+

vote_comment_like:
  methods: [ POST ]
  path: /comment/{commentId}/like

vote_comment_dislike:
  methods: [ POST ]
  path: /comment/{commentId}/dislike

vote_comment_update:
  methods: [ POST ]
  path: /comment/{commentId}/update