services:
    auth.account.repository:
        class: AccountBundle\Repository\AccountRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - AccountBundle\Entity\Account

    account.service:
        class: AccountBundle\Service\AccountService
        arguments:
          - '@fos_user.user_manager'
          - '@event_dispatcher'
          
    account.listener.role:
      class: AccountBundle\EventListener\RoleListener
      arguments: ['@auth.account.repository']
      tags:
        - { name: kernel.event_subscriber }