sign_in:
  path: /sign-in
  methods: [POST]

sign_up:
  path: /sign-up
  defaults:
    _controller: AuthBundle:SignUp:signUp
  methods: [PUT]

get_token:
  path: /token/get/{token}/{refresh_token}
  defaults:  
    _controller: AuthBundle:RenderToken:render
  methods: [GET]
  
refresh_token:
  path:     /token/refresh
  defaults: 
   _controller: AuthBundle:RefreshToken:refresh 
  methods: [POST]