services:
    auth.event.jwt_created_listener:
        class: AuthBundle\EventListener\JWTCreatedListener
        arguments: [ '@profile.service' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }